name: "Workflow for Feature branches"

on:
  push:
    branches-ignore:
      - main

jobs:
  solidity:
    uses: Byte-Masons/workflows/.github/workflows/solidity.yml@main
    with:
      working-directory: ./src
      analysis-enabled: false
      lint-enabled: false
